.\"Man Page for Emdaemon
.TH Emdaemon 1 "18 August 2021" "UKUI Desktop Environment"
.SH "NAME"
Emdaemon \- Shortcut key daemon 
.SH "SYNOPSIS"
.B emdaemon
.SH "DESCRIPTION"
OSD Daemon1 applications
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by: 
sundagao <sundagao@kylinos.cn> (2021)
 
