.\"Man Page for Kydisplayswitch
.TH Kydisplay 1 "18 August 2021" "UKUI Desktop Environment"
.SH "NAME"
Kydisplayswitch \- Gui tool for display switching
.SH "SYNOPSIS"
.B kydisplayswitch
.SH "DESCRIPTION"
Kydisplayswitch is Gui tool for display switching
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by: 
sundagao <sundagao@kylinos.cn> (2021)
 
