.\"Man Page for Mktip
.TH Mktip 1 "18 August 2021" "UKUI Desktop Environment"
.SH "NAME"
Mktip \- Hotkey status 
.SH "SYNOPSIS"
.B mktip
.SH "DESCRIPTION"
OSD Hotkey status 
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by: 
sundagao <sundagao@kylinos.cn> (2021)
 
