#!/bin/sh

set -e

#systemctl enable kylin-display-switch.service

linkfile="/usr/bin/super_kds"
test -L $linkfile && `rm $linkfile`
ln -s /usr/share/kylin-display-switch/super_kylin_display_switch.py $linkfile
